### ISSUE TITLE
autofdo does not build with protobuf-34.2

### ISSUE THREAD

**Issue by andikleen** [google/autofdo#265]
As is the default install on my opensuse tumbleweed system:

Lots of errors like:

[  1%] Building CXX object CMakeFiles/perf_proto.dir/third_party/perf_data_converter/src/quipper/perf_data.pb.cc.o
In file included from /src2/src2/autofdo/build/third_party/perf_data_converter/src/quipper/perf_data.pb.h:21,
                 from /src2/src2/autofdo/build/third_party/perf_data_converter/src/quipper/perf_data.pb.cc:6:
/usr/include/google/protobuf/io/coded_stream.h:151:61: error: variable ‘google::protobuf::io::ABSL_ATTRIBUTE_WARN_UNUSED google::protobuf::io::CodedInputStream’ has initializer but incomplete type
  151 | class PROTOBUF_EXPORT PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED CodedInputStream {
      |                                                             ^~~~~~~~~~~~~~~~
/usr/include/google/protobuf/io/coded_stream.h:152:2: error: expected primary-expression before ‘public’
  152 |  public:
      |  ^~~~~~
/usr/include/google/protobuf/io/coded_stream.h:152:2: error: expected ‘}’ before ‘public’
/usr/include/google/protobuf/io/coded_stream.h:151:78: note: to match this ‘{’
  151 | class PROTOBUF_EXPORT PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED CodedInputStream {
      |                                                                              ^
/usr/include/google/protobuf/io/coded_stream.h:152:2: note: probably missing a comma or an operator before
  152 |  public:
      |  ^~~~~~
/usr/include/google/protobuf/io/coded_stream.h:643:5: error: variable ‘google::protobuf::io::ABSL_ATTRIBUTE_WARN_UNUSED google::protobuf::io::EpsCopyOutputStream’ has initializer but incomplete type
  643 |     EpsCopyOutputStream {
      |     ^~~~~~~~~~~~~~~~~~~
/usr/include/google/protobuf/io/coded_stream.h:644:2: error: expected primary-expression before ‘public’

**Comment by andikleen** [comment]
full log file:
[l.txt](https://github.com/user-attachments/files/29276262/l.txt)

**Comment by andikleen** [comment]
I tried to edit the protobuf file to comment out the missing ABSL defines, with that it gets further but eventually still fails with more conflicts.

I'm not sure what the problem is exactly. Maybe absl needs an update? Or need to support protobufs as a vendored library.
